# Generated by Django 4.1.3 on 2022-12-06 20:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0010_doctor_user_patient_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='fname',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='lname',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='mname',
        ),
    ]
